# NOTE: ConnectionStrings gets the IP of the Postgres Service via "Server=postgres-clusterip" erm
# as same as we have on docker compose
apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-svc
spec:
  selector:
    matchLabels:
      app: action-svc
  template:
    metadata:
      labels:
        app: action-svc
    spec:
      containers:
        - name: action-svc
          image: henriquequeirozcunha/auction-svc
          imagePullPolicy: Never
          env:
            - name: RabbitMq__Host
              value: rabbit-cluster-ip
            - name: RabbitMq__Username
              value: rabbit
            - name: RabbitMq__Password
              value: rabbit
            - name: ConnectionStrings__DefaultConnection
              value: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=auctions
            - name: IdentityServiceUrl
              value: http://identity-svc # This will point to some external hosted service such as Digital Ocean DNS....
            - name: Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: Kestrel__Endpoints__Grpc__Url
              value: http://+:7777
            - name: Kestrel__Endpoints__WebApi__Protocols
              value: Http1
            - name: Kestrel__Endpoints__WebApi__Url
              value: http://+:80

---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  selector:
    app: auction-svc
  ports:
    - port: 80
      targetPort: 80
      name: web
    - port: 7777
      targetPort: 7777
      name: grpc
