apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
        - name: bid-svc
          image: henriquequeirozcunha/bid-svc
          imagePullPolicy: Never
          env:
            - name: RabbitMq__Host
              value: rabbit-cluster-ip
            - name: RabbitMq__Username
              value: rabbit
            - name: RabbitMq__Password
              value: rabbit
            - name: ConnectionStrings__BidDbConnection
              value: mongodb://root:mongopw@mongo-clusterip
            - name: IdentityServiceUrl
              value: http://identity-svc # This will point to some external hosted service such as Digital Ocean DNS....
            - name: GrpcAuction
              value: http://auction-clusterip:7777

---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
    - port: 80
      targetPort: 80
