apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
        - name: gateway-svc
          image: henriquequeirozcunha/gateway-svc
          imagePullPolicy: Always # NOTE: Change it to Never if running locally
          env:
            - name: ClientApp
              value: https://app.carsties.com # NOTE: this is the REAL DNS. TO work a domain has to be purchased, point to a load balancer on Digital Ocean.
            - name: IdentityServiceUrl
              value: http://identity-svc # This will point to some external hosted service such as Digital Ocean DNS....

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
    - port: 80
      targetPort: 80
