apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: henriquequeirozcunha/web-app
          imagePullPolicy: Never
          env:
            - name: NEXTAUTH_SECRET
              value: nextsecret
            - name: NEXTAUTH_URL
              value: https://app.carsties.com
            - name: API_URL
              value: http://gateway-clusterip/
            - name: IDENTITY_SERVER_URL
              value: http://id.carsties.com # This will point to some external hosted service such as Digital Ocean DNS....
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000
