name: deploy-auction

on:
  workflow_dispatch:
  push:
    branches: ['master']
    paths:
      - 'src/AuctionService/**'

env:
  REGISTRY_IMAGE: henriquequeirozcunha/auction-svc
  DOCKERFILE: src/AuctionService/Dockerfile
  DEPLOYMENT_NAME: auction-svc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: '{{defaultContext}}'
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save carsties # NOTE: ESAVE CONTEXT ON KUBERNETES TO BE ABLE TO RUN KUBCTL COMMANDS
      - name: Restart kubernetes deployment
        run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }} # NOTE: Name of deployment. Look into "auction-deply.yml"
